Refactor `Base` class to use `DeclarativeBase` for SQLAlchemy 2.0+ (#157)
# Description

1. Replaced the use of `declarative_base` with Base class inheriting from`DeclarativeBase` to align with the usage pattern in SQLAlchemy 2.0+.
2. Created a new TypeVar ModelType for `table` types in `etl/data_handler` and `soft_story_properties_data_handler`. This fixes type hint errors due to previous `DeclarativeMedia` type.
eg:
```
backend/etl/soft_story_properties_data_handler.py:120: 
error: Argument 2 to "_SoftStoryPropertiesDataHandler" has incompatible type "type[SoftStoryProperty]"; 
expected "DeclarativeMeta"  [arg-type]
```

I still haven't set my local environment yet, so didn't run any tests on this change. Happy to continue working on my local setup, if this is not acceptable.

https://github.com/sfbrigade/datasci-earthquake/issues/117

## Type of changes
- [ ] Bugfix
- [x] Chore
- [ ] New Feature

## Testing
- [ ] I added automated tests
- [x] I think tests are unnecessary